apiVersion: apps/v1
kind: Deployment
metadata:
  name: subresource-server-example
spec:
  selector:
    matchLabels:
      name: subresource-server-example
  template:
    metadata:
      labels:
        name: subresource-server-example
    spec:
      serviceAccountName: subresource-server-example
      containers:
        - name: subresource-server-example
          image: subresource-server-example
          ports:
            - containerPort: 8443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subresource-server-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subresource-server-example-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: default
    name: subresource-server-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subresource-server-example
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    namespace: default
    name: subresource-server-example
---
apiVersion: v1
kind: Service
metadata:
  name: subresource-server-example
spec:
  selector:
    name: subresource-server-example
  ports:
    - port: 443
      targetPort: 8443
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.subresource.example.org
spec:
  group: subresource.example.org
  groupPriorityMinimum: 2000
  version: v1alpha1
  versionPriority: 10
  service:
    namespace: default
    name: subresource-server-example
  insecureSkipTLSVerify: true
